### ISSUE TITLE
Consider adding additional docker-compose commands

### ISSUE THREAD

**Issue by maddenj-ie** [vogoltsov/robotframework-docker#14]
Hi,

Would you consider additional support for the following docker-compose commands:

- start
- stop
- restart
- pause
- unpause
- kill
- etc. ;-)

I'm using the library for system tests where a docker-compose file is used for the test deployment and it would be very useful to be able to manipulate the test deployment in order to stop/start or kill or pause/unpause specific services to validate the behaviour of the target services under these kind of failure scenarios.

Thanks for consideration.  Regards.

**Comment by vogoltsov** [comment]
Added keywords for:
* version
* kill
* start
* stop
* restart
* pause
* unpause
