### ISSUE TITLE
Various docker compose commands don't work if suite name has uppercase letters.

### ISSUE THREAD

**Issue by dries007** [vogoltsov/robotframework-docker#15]
Hey,

I've noticed that, when my suite name contains uppercase letters, the `docker compose logs` keywords returns an empty string.
When I manually overwrite the project_name parameter of the library or add a `.lower()` on the `get_variable_value('${SUITE NAME}')`, everything works again.

Discovered because I noticed by that the names of the containers are all lowercase when manually running `docker ps`.

Kind regards,
Dries

**Comment by vogoltsov** [comment]
Thanks for reporting!
Fixed by replacing all unsuitable characters with underscore and then calling `lower()` as suggested.
