### ISSUE TITLE
Support Robot LSP inspection

### ISSUE THREAD

**Issue by MHHenriksen** [vogoltsov/robotframework-docker#30]
When trying to use your library, I get this error in vscode on the `Library  DockerComposeLibrary` line:

> Unresolved library: DockerComposeLibrary.
> Error generating libspec:
> Initializing library 'DockerComposeLibrary' with no arguments failed: RobotNotRunningError: Cannot access execution context `robotframework`

Consequently, all the Docker keywords also get red squiggles and show as undefined in the tooltip.

I'm using this extension: https://marketplace.visualstudio.com/items?itemName=robocorp.robotframework-lsp

The library works fine when running my test case with Robot Framework, btw. So most likely you just need to refactor some initialization code to only run the first time a keyword is invoked, or just do something differently so as not to depend on the execution context.

**Comment by MHHenriksen** [comment]
Found the stack trace in the output panel!

```
Traceback (most recent call last):

  File "C:\code\rob2\.micromamba\envs\robot\Lib\site-packages\DockerComposeLibrary.py", line 60, in __init__

    self._project_name = re.sub(r'\W', '_', BuiltIn().get_variable_value('${SUITE NAME}'), re.ASCII).lower()

                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\code\rob2\.micromamba\envs\robot\Lib\site-packages\robot\libraries\BuiltIn.py", line 1502, in get_variable_value

    name = self._get_var_name(name, require_assign=False)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\code\rob2\.micromamba\envs\robot\Lib\site-packages\robot\libraries\BuiltIn.py", line 1780, in _get_var_name

    replaced = self._variables.replace_string(original)

               ^^^^^^^^^^^^^^^

  File "C:\code\rob2\.micromamba\envs\robot\Lib\site-packages\robot\libraries\BuiltIn.py", line 71, in _variables

    return self._namespace.variables

           ^^^^^^^^^^^^^^^

  File "C:\code\rob2\.micromamba\envs\robot\Lib\site-packages\robot\libraries\BuiltIn.py", line 67, in _namespace

    return self._get_context().namespace

           ^^^^^^^^^^^^^^^^^^^

  File "C:\code\rob2\.micromamba\envs\robot\Lib\site-packages\robot\libraries\BuiltIn.py", line 62, in _get_context

    raise RobotNotRunningError('Cannot access execution context')

robot.libraries.BuiltIn.RobotNotRunningError: Cannot access execution context


```

**Comment by MHHenriksen** [comment]
Here's an old issue in the LSP repo discussing the same problem for a different library: https://github.com/robocorp/robotframework-lsp/issues/166

**Comment by vogoltsov** [comment]
As I see it, LSP tries to get access to the library instance (for introspection?), but assumes the library would not initialise itself before being used or doesn't depend on Robotframework during initialisation.

As initialising a library in `__init__` seems to be the official correct way to do it in Robotframework, this assumption is wrong. That's why they suggest to defer initialisation in the library.

As this is not that big of an issue with this library, I fixed it by catching the `RobotNotRunningError`. But overall I think it's more of an issue of LPS making incorrect presumptions about the library lifecycle.

Could you give this a try in version `1.4.2`?

**Comment by MHHenriksen** [comment]
Thanks for the fix, it did the trick!
![image](https://github.com/vogoltsov/robotframework-docker/assets/20283377/31b5d761-42b8-4d6c-baf2-f57ee4a0bb2c)

And I agree with your argument here, the LSP devs got this one wrong.
